name: build-test
on:
  push:
  pull_request:



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4.1.7
      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # pin@5.0.2
        with:
          go-version: '1.22'
      - name: Test source headers are present
        run: make test-source-headers
      - name: Run unit tests
        run: make test-coverage
      - name: Test build
        run: make build
      - name: Run govulncheck
        uses: golang/govulncheck-action@dd0578b371c987f96d1185abb54344b44352bd58 # pin@1.0.3
        with:
          go-package: ./...